#version: '3.8'

services:
  django:
    build: .
    volumes:
      - .:/ecommerce
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - "main"
    restart: always

  nuxt-app:
    build:
      context: https://github.com/taymakz/zariny-ecommerce-dashboard.git
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    networks:
      - "main"
    restart: unless-stopped

networks:
  main:
