version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/ecommerce
      - database:/ecommerce/sandbox/sqlite
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always
    command: >
         sh -c "python sandbox/manage.py migrate &&
         python sandbox/manage.py runserver 0.0.0.0:8000"

volumes:
  database:

networks:
  main:
